# -*- coding: utf-8 -*-
"""DataMining_Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1902VmMlMUl5_FhddewKrNulmpGPZMHLl
"""

#pandas
import pandas as pd
df = pd.read_csv("/content/hotel_bookings.csv")

df.describe()

df.head(5)

df.tail(5)

a=pd.Series(df.hotel)
print(a)

#matplotlib

import matplotlib.pyplot as plt

plt.scatter(df.arrival_date_day_of_month,df.stays_in_week_nights)
plt.xlabel("Arrival Date of a month")
plt.ylabel("Stays in week nights")

roomCount=df.assigned_room_type.value_counts()
plt.bar(roomCount.index,roomCount,linewidth=0.5,edgecolor="white")

plt.hist(df.arrival_date_month,linewidth=0.5,edgecolor="white")
plt.xlabel("Months")
plt.ylabel("No. of guests")

sns.heatmap(df.corr())

import seaborn as sns

#CountPlot (Bivariate)
sns.countplot(x="adults",data=df)

#numpy

import numpy as np

Mean = df.mean(axis=0,skipna=True)

for col in df.select_dtypes(include=np.number).columns:
  per = ((df[col].isnull().sum())/(len(df[col])))*100
  print(per)
  if per>=80:
    df.drop(df[col],axis=1,inplace=True)
  else:
    df[col].fillna(Mean[col],inplace=True)

print(df.isnull().sum())
print(df['agent'])

mean = df.mean(axis = 0, skipna = True)
for col in df.select_dtypes(include=np.number).columns:
  if (df[col].isnull().sum()/len(df[col]) * 100) > 80:
    df.drop(col, axis=1, inplace = True)
  else:
    df[col].fillna(mean[col], inplace = True)


print(df.isnull().sum())
print(df['agent'])