# -*- coding: utf-8 -*-
"""DataMining_Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqBL1JJrTe8aZrkys8m4IeZw8nl_GAia
"""

import pandas as pd

df = pd.read_csv('train.csv')
df.head()

df.dtypes

import scipy.stats as stats

#Zscore Scaling
df_zscore_scaled = df.copy()

for column in df_zscore_scaled.select_dtypes(include='float64').columns:
	df_zscore_scaled[column] = (df_zscore_scaled[column] - df_zscore_scaled[column].mean()) / df_zscore_scaled[column].std()

print(df_zscore_scaled.select_dtypes(include='float64'))

#Min-Max Scaling
df_min_max_scaled = df.copy()

for column in df_min_max_scaled.select_dtypes(include='float64').columns:
    df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

print(df_min_max_scaled.select_dtypes(include='float64'))

#Mean Normalization Scaling
df_MeanNormalization_Scaled = df.copy()

for column in df_MeanNormalization_Scaled.select_dtypes(include='float64').columns:
  df_MeanNormalization_Scaled[column] = (df_MeanNormalization_Scaled[column]-df_MeanNormalization_Scaled[column].mean())/(df_MeanNormalization_Scaled[column].max()-df_MeanNormalization_Scaled[column].min())

print(df_MeanNormalization_Scaled.select_dtypes(include='float64'))

#MaxAbsolute Scaling
df_MaxAbsolute_scaled = df.copy()

for column in df_MaxAbsolute_scaled.select_dtypes(include='float64').columns:
    df_MaxAbsolute_scaled[column] = df_MaxAbsolute_scaled[column]  / df_MaxAbsolute_scaled[column].abs().max()

print(df_MaxAbsolute_scaled.select_dtypes(include='float64'))

#Robust Scaling
df_robust_scaled = df.copy()

for column in df_robust_scaled.select_dtypes(include = 'float64').columns:
  df_robust_scaled[column] = (df_robust_scaled[column] - df_robust_scaled[column].median())  / (df_robust_scaled[column].quantile(0.75) - df_robust_scaled[column].quantile(0.25))

print(df_robust_scaled.select_dtypes(include='float64'))