# -*- coding: utf-8 -*-
"""DataMining_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtpv2uYhD8j9GoILXPk9muyJleHDQsdm
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(10)
data = np.random.normal(0, 1.5, 200)

#Histogram
fig,his=plt.subplots()
his.hist(data,linewidth=0.5,edgecolor="white")
plt.show()

#ScatterPlot
data_output = np.random.normal(0,1.5,len(data))

fig,sca = plt.subplots()
sca.scatter(data,data_output)
plt.show()