# -*- coding: utf-8 -*-
"""DataMining_Lab2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSOYnd5RMWvQWvXFglfv3eern04C16ND
"""

import pandas as pd
data = pd.read_csv('train_u6lujuX_CVtuZ9i.csv')

data.describe()

data.head(8)

import matplotlib.pyplot as plt

#Histogram (Univariate)
plt.hist(data.Loan_Amount_Term,linewidth=0.5,edgecolor="white")
plt.xlabel("Index")
plt.ylabel("Loan Amount Term")

# Violin Plot (Univariate)
plt.violinplot(data.CoapplicantIncome)
plt.xlabel("CoApplicant Income")

#BarGraph (Univariate)
genderCount=data.Gender.value_counts()
plt.bar(genderCount.index,genderCount,linewidth=0.5,edgecolor="white")

#ScatterPlot (Bivariate)
plt.scatter(data.ApplicantIncome,data.LoanAmount)
plt.xlabel("Applicant Income")
plt.ylabel("Loan Amount")

import seaborn as sns

#CountPlot (Bivariate)
sns.countplot(x="Education",data=data,hue="Loan_Status")

#BarPlot (Bivariate)
sns.barplot(data,x="Gender",y="ApplicantIncome")

#HeatMap (Multivariate)
sns.heatmap(data.corr(),annot=True)

#BarPlot (Multivariate)

sns.barplot(data,x="Gender",y="ApplicantIncome",hue="Loan_Status")